### PR TITLE
Batch searched GitHub for new themes

### PR DESCRIPTION
**Pull request by mushishi78**
I wrote a script to search GitHub for Jekyll projects and parse them into a `_drafts` folder. A lot of the projects are blogs, or tools, or abandoned, or duplicates...etc, but I'm sure there are some good themes in there. We could also start a "In the Wild" or a tools list as separate collections.

As this pull request might never get merged in if we wait to check all of them, and as the _drafts folder will have no effect on the live site, I suggest that we merge them in and then go through them on the main branch over time.

### CODE REVIEW

**Comment by gynter** [comment]
I did similar like a month ago and also ended up with huge amount of dead and duplicated things. Sorting this out by hand imo is impossible. Also as You stated, the list probably contains lots of dead things, since Github Pages are quite easy to use for temporary stuff too.

Imo merging it (even to `_drafts/`) will only cause mess to the source three which probably no-one has really time to fully sort out.

**Comment by mushishi78** [comment]
That's a fair appraisal. I'll leave as a branch then.

Here's a list of good candidates to start with. They've all mention either the word "theme" or "template", they have licence files and they have a demo/website:

2011-01-27-jamesyu_jekyll_template
2012-01-19-hekyll
2012-04-16-jekyll-deck
2012-12-14-up
2013-04-05-jekyller
2013-07-16-strongly-typed-jekylled
2013-11-13-gigaspaces-wiki-jekyll
2013-12-10-jekyll-revealjs
2014-01-22-jekyll-course-template
2014-01-27-jekyll_app_site
2014-06-07-Artists-Theme
2014-06-30-white-paper
2014-08-05-rzl-homepage
2014-08-22-jekyll-clean
2014-10-05-jekyll-material-design
2014-12-11-slim-pickins-jekyll-theme
2014-12-14-long-haul
2014-12-25-comical-jekyll-theme
2015-01-07-type-theme
2015-01-20-timeline-jekyll-theme
2015-01-23-jekyll-qck-theme
2015-01-29-huxpro.github.io
2015-04-09-jekyll-materiallize
2015-05-03-vida
2015-07-11-jekyll-mdl

**Comment by jacobtomlinson** [comment]
Did you produce that list by hand or with a script? As @gynter said doing this by hand is not scalable.

**Comment by mushishi78** [comment]
By [script](https://github.com/jekyllrc/jekyllthemes/blob/f57e389ee4350a639bfdb8b40239b5804adf9deb/_scripts/reports/draft_candidates.txt), though I did edit out a few by eye.

**Pull request closed without merging**
